logging.level.com.orange: DEBUG

# --- DB - H2

#spring.h2.console:
#  enabled: true
#  path: /h2

# --- DB - MySQL

#spring.jpa.hibernate.ddl-auto: update
#spring.datasource:
#  url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/movie-ticket-reservation
#  username: root
#  password: secret

# --- DB - common

#spring.jpa.properties.hibernate:
#  generate_statistics: false
#  show_sql: true
#  format_sql: true

# --- actuator

#management.endpoints.web.exposure.include: '*'

# --- db populator

hall.seats: 200

movie.names:
  - movieA
  - movieB
  - movieC
